---
# Playbook to set up a Debian node with a CUDA driver, NVIDIA Container Toolkit, and Docker

- hosts: all
  become: yes
  tasks:
  - name: Install docker prerequisites
    apt:
      pkg:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - wget
        - software-properties-common
      update_cache: yes

  - name: Add non-free repositories
    ansible.builtin.shell: apt-add-repository non-free

  - name: Add docker keyring
    ansible.builtin.shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    args:
      creates: /usr/share/keyrings/docker-archive-keyring.gpg

  - name: Install docker sources
    ansible.builtin.shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    args:
      creates: /etc/apt/sources.list.d/docker.list

  - name: Install docker packages
    apt:
      pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
      update_cache: yes

  - name: Install packages for NVIDIA runfile
    apt:
      pkg:
        - "linux-headers-{{ ansible_kernel }}"
        - gcc
        - make

  - name: Download driver runfile
    ansible.builtin.shell: wget https://us.download.nvidia.com/XFree86/Linux-x86_64/510.68.02/NVIDIA-Linux-x86_64-510.68.02.run
    args:
      creates: NVIDIA-Linux-x86_64-510.68.02.run

  - name: Execute CUDA driver runfile
    ansible.builtin.shell: sh NVIDIA-Linux-x86_64-510.68.02.run --silent

  - name: Install container toolkit sources
    ansible.builtin.shell: distribution=$(. /etc/os-release;echo $ID$VERSION_ID) && curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg && curl -s -L https://nvidia.github.io/libnvidia-container/$distribution/libnvidia-container.list | sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
    args:
      creates: /etc/apt/sources.list.d/nvidia-container-toolkit.list

  - name: Install nvidia docker runtime
    apt:
      name: nvidia-docker2
      update_cache: yes

  - name: Restart docker
    ansible.builtin.systemd:
      state: restarted
      name: docker

  - name: Test access to GPU within container
    ansible.builtin.shell: docker run --rm --gpus all nvidia/cuda:11.6.0-base-ubuntu20.04 nvidia-smi
    register: command_output

  - debug:
      var: command_output.stdout_lines

