---

west:
  hosts:
    piranha1:
      ansible_host: 54.188.114.253
    piranha2: 
      ansible_host: 52.35.252.170 
  vars:
    ansible_user: ubuntu

east:
  hosts:
    piranha1:
      ansible_host:
    piranha2: 
      ansible_host:
    piranha3: 
      ansible_host:
    piranha4: 
      ansible_host:
  vars:
    ansible_user: ubuntu


